name: Create .env file and access to secrets

on:
  push:
    branches:
      - main  # Adjust with your branch name

jobs:
  access-to-secrets: # 아무이름이나 해주면 됨
    name: access to secrets
    runs-on: ubuntu-latest
    steps:
      - name: access to secrets
        run: |
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }} >> .env
          echo msy_naver_papago_api_id=${{ secrets.msy_naver_papago_api_id }} >> .env
          echo msy_naver_papago_api_secret=${{ secrets.msy_naver_papago_api_secret }} >> .env
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          HUGGINGFACEHUB_API_TOKEN: ${{secrets.HUGGINGFACEHUB_API_TOKEN}}
          msy_naver_papago_api_id: ${{secrets.msy_naver_papago_api_id}}
          msy_naver_papago_api_secret: ${{secrets.msy_naver_papago_api_secret}}
