name: Create .env file and access to secrets

on:
  push:
    branches:
      - main  # Adjust with your branch name

jobs:
  access-to-secrets: # 아무이름이나 해주면 됨
    name: access to secrets
    runs-on: ubuntu-latest
    steps:
      - name: access to secrets
        run: |
          echo "MAP_API_KEY=$MAP_API_KEY" >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }} >> .env
          echo msy_naver_papago_api_id=${{ secrets.msy_naver_papago_api_id }} >> .env
          echo msy_naver_papago_api_secret=${{ secrets.msy_naver_papago_api_secret }} >> .env
        env:
          MAP_API_KEY: ${{secrets.MAP_API_KEY}}
